package com.hereliesaz.hg2gui.managers

data class GuideCategory(val title: String, val description: String, val items: List<GuideItem>)
data class GuideItem(val command: String, val description: String)

object TermuxHandbook {

    val categories = listOf(

        GuideCategory(
            title = "Chapter 1: The Termux Foundation",
            description = "This chapter covers the absolute essentials for managing the Termux environment itself, installing tools, and performing basic file system navigation. Mastering these commands is the first and most critical step.",
            items = listOf(
                GuideItem("pkg update", "Updates the list of available packages from your subscribed repositories."),
                GuideItem("pkg upgrade", "Upgrades all installed packages to their latest versions."),
                GuideItem("pkg install <package>", "Installs a specific package, like `termux-api`."),
                GuideItem("pkg uninstall <package>", "Removes a package from your system."),
                GuideItem("pkg reinstall <package>", "Reinstalls a package, which can fix broken installations."),
                GuideItem("pkg list-installed", "Shows a list of all packages you have installed."),
                GuideItem("pkg search <query>", "Searches for available packages."),
                GuideItem("pkg show <package>", "Displays detailed information about a specific package."),
                GuideItem("pkg files <package>", "Lists all files that a specific package installed."),
                GuideItem("termux-setup-storage", "Prompts for permission to access the device's shared storage."),
                GuideItem("pwd", "Displays the full path of your current directory."),
                GuideItem("ls", "Lists the files and folders in your current location."),
                GuideItem("cd", "Changes your current directory (`cd ..` goes up, `cd ~` goes home)."),
                GuideItem("clear", "Wipes the terminal screen clean."),
                GuideItem("exit", "Closes the current Termux session."),
                GuideItem("mkdir <name>", "Creates a new directory."),
                GuideItem("touch <filename>", "Creates a new, empty file."),
                GuideItem("rm <filename>", "Deletes a file. Use `rm -r <directory>` to delete a directory."),
                GuideItem("cp <source> <destination>", "Copies a file or directory."),
                GuideItem("mv <source> <destination>", "Moves or renames a file or directory."),
                GuideItem("whoami", "Displays the current username (e.g., `u0_a123`)."),
                GuideItem("uname -o", "Displays the operating system (Android)."),
                GuideItem("df -h", "Shows disk space usage in a human-readable format."),
                GuideItem("top", "Displays a live view of running processes and system resource usage."),
                GuideItem("ping <host>", "Checks network connectivity to a server (e.g., `ping google.com`)."),
                GuideItem("ifconfig", "Displays your device's network interface information and IP address."),
            )
        ),
        GuideCategory(
            title = "Chapter 2: Interacting with the Android UI",
            description = "These commands, primarily from the `termux-api` package, allow your scripts to break out of the terminal and interact directly with the Android user interface, creating a bridge between the command line and the graphical environment.",
            items = listOf(
                GuideItem("termux-toast \"message\"", "Shows a small, temporary pop-up message (a \"toast\")."),
                GuideItem("termux-dialog", "Creates a pop-up dialog box to get text input from the user."),
                GuideItem("termux-dialog checkbox -v \"Option1,Option2\"", "Creates a dialog with selectable checkboxes."),
                GuideItem("termux-dialog confirm -t \"Question?\"", "Creates a pop-up with \"Yes\" and \"No\" buttons."),
                GuideItem("termux-dialog counter -r \"1,10,5\"", "Creates a dialog to select a number within a range (min, max, start)."),
                GuideItem("termux-dialog date", "Creates a dialog with a date picker."),
                GuideItem("termux-dialog radio -v \"Choice1,Choice2\"", "Creates a dialog with radio button options (only one can be selected)."),
                GuideItem("termux-dialog sheet -v \"Item1,Item2\"", "Creates a bottom sheet with selectable items."),
                GuideItem("termux-dialog spinner -v \"Value1,Value2\"", "Creates a dialog with a dropdown spinner menu."),
                GuideItem("termux-dialog speech -t \"Say something\"", "Opens a dialog to get voice input from the user."),
                GuideItem("termux-dialog time", "Creates a dialog with a time picker."),
                GuideItem("termux-notification --title \"Alert\"", "Posts a notification to the Android notification drawer."),
                GuideItem("termux-notification-remove <id>", "Removes a notification that was created by Termux."),
                GuideItem("termux-clipboard-get", "Prints the current content of the system clipboard."),
                GuideItem("termux-clipboard-set \"text\"", "Sets the system clipboard to the specified text."),
                GuideItem("termux-open <URL>", "Opens a URL in the default web browser."),
                GuideItem("termux-open <file>", "Opens a file with its default Android application."),
                GuideItem("termux-share <file>", "Opens the Android share dialog for a specific file."),
                GuideItem("termux-wallpaper -f <image_file>", "Sets the device's home screen wallpaper from a local file."),
                GuideItem("termux-wallpaper -u <image_url>", "Sets the wallpaper from an image URL."),
                GuideItem("termux-get-prop <property>", "Gets an Android system property value."),
                GuideItem("termux-vibrate", "Vibrates the device for a short period."),
                GuideItem("termux-vibrate -d <milliseconds>", "Vibrates the device for a specified duration."),
                GuideItem("termux-vibrate -f", "Forces vibration even if the device is in silent mode."),
                GuideItem("termux-job-scheduler", "Schedules a script to be run at a later time, even if Termux is closed."),
                GuideItem("logcat -d", "Dumps the Android system log to the console and exits."),
            )
        ),
        GuideCategory(
            title = "Chapter 3: Accessing Device Hardware",
            description = "Go beyond software and command your device's physical components. The Termux API provides direct control over the camera, flashlight, sensors, and more, turning your phone into a programmable, real-world tool.",
            items = listOf(
                GuideItem("termux-battery-status", "Returns a JSON object with battery level, temperature, and health."),
                GuideItem("termux-camera-info", "Returns JSON data about the available camera(s) on the device."),
                GuideItem("termux-camera-photo -c 0 image.jpg", "Takes a photo using the specified camera (e.g., camera 0) and saves it."),
                GuideItem("termux-torch on", "Turns the flashlight on."),
                GuideItem("termux-torch off", "Turns the flashlight off."),
                GuideItem("termux-sensor", "Dumps a list of all available sensors and their names."),
                GuideItem("termux-sensor -s \"accelerometer\"", "Starts streaming live data from a specific sensor."),
                GuideItem("termux-sensor -n 1 -d 500", "Gets a single reading from all sensors with a delay."),
                GuideItem("termux-sensor -c", "Cleans up (stops) all running sensor listeners."),
                GuideItem("termux-tts-engines", "Lists the available Text-To-Speech (TTS) engines on the device."),
                GuideItem("termux-tts-speak \"Hello from Termux\"", "Uses the default TTS engine to speak text aloud."),
                GuideItem("termux-tts-speak -e <engine> \"Text\"", "Speaks text using a specific TTS engine."),
                GuideItem("termux-tts-speak -p <pitch>", "Speaks text with a specified vocal pitch (e.g., `1.5` for higher)."),
                GuideItem("termux-tts-speak -r <rate>", "Speaks text at a specified speech rate (e.g., `0.5` for slower)."),
                GuideItem("termux-microphone-record", "Starts recording audio from the microphone."),
                GuideItem("termux-microphone-record -f rec.wav -l 5", "Records for 5 seconds and saves to a file."),
                GuideItem("termux-microphone-record -q", "Quits the current recording."),
                GuideItem("termux-media-player play <file>", "Plays a media file (audio or video)."),
                GuideItem("termux-media-player pause", "Pauses the currently playing media."),
                GuideItem("termux-media-player stop", "Stops the currently playing media."),
                GuideItem("termux-media-player info", "Displays information about the currently playing media."),
                GuideItem("termux-volume", "Lists all available audio streams and their volume levels."),
                GuideItem("termux-volume <stream> <level>", "Sets the volume for a specific stream (e.g., `termux-volume music 10`)."),
                GuideItem("termux-fingerprint", "Prompts for fingerprint authentication and returns success or failure."),
                GuideItem("termux-infrared-frequencies", "Gets the available infrared carrier frequencies (on supported devices)."),
                GuideItem("termux-infrared-transmit -f <freq> <pattern>", "Transmits an infrared pattern."),
            )
        ),
        GuideCategory(
            title = "Chapter 4: Communication & Connectivity",
            description = "Automate and manage your device's core communication features. These API commands allow you to send SMS, initiate calls, query contacts, and control Wi-Fi connections, all from your scripts.",
            items = listOf(
                GuideItem("termux-telephony-call <number>", "Initiates a phone call to the specified number."),
                GuideItem("termux-telephony-cellinfo", "Returns JSON data about neighboring cell towers."),
                GuideItem("termux-telephony-deviceinfo", "Returns JSON data about the device's telephony capabilities."),
                GuideItem("termux-contact-list", "Returns a JSON list of all contacts on the device."),
                GuideItem("termux-sms-list", "Returns a JSON list of recent SMS messages."),
                GuideItem("termux-sms-list -l 50", "Lists the last 50 SMS messages."),
                GuideItem("termux-sms-send -n <number> \"Msg\"", "Sends an SMS to a specific number."),
                GuideItem("termux-sms-send -n <num1,num2> \"Hi\"", "Sends an SMS to multiple numbers at once."),
                GuideItem("termux-wifi-connectioninfo", "Returns JSON data about the current Wi-Fi connection (SSID, IP, etc.)."),
                GuideItem("termux-wifi-scaninfo", "Returns a JSON list of nearby Wi-Fi networks."),
                GuideItem("termux-wifi-enable true", "Turns Wi-Fi on."),
                GuideItem("termux-wifi-enable false", "Turns Wi-Fi off."),
                GuideItem("termux-location", "Returns JSON data with the device's last known GPS location."),
                GuideItem("termux-location -p <provider>", "Gets location from a specific provider (`gps`, `network`, or `passive`)."),
                GuideItem("termux-location -r <request_type>", "Specifies a single (`once`) or continuous (`last`) update."),
                GuideItem("termux-download <URL>", "Downloads a file using the Android system download manager."),
                GuideItem("termux-download -t \"Title\" <URL>", "Downloads a file with a custom title in the notification."),
                GuideItem("netstat", "Shows network connections, routing tables, and interface statistics."),
                GuideItem("ip addr", "A modern command to show IP addresses and network interface information."),
                GuideItem("ip route", "Displays the current IP routing table."),
                GuideItem("ss", "A utility to investigate sockets (a modern replacement for `netstat`)."),
                GuideItem("proot", "Emulates `chroot`, allowing you to run programs with a different root directory."),
                GuideItem("proot-distro install <alias>", "Installs a full Linux distribution (like Ubuntu) inside Termux."),
                GuideItem("proot-distro login <alias>", "Starts a shell inside the installed Linux distribution."),
                GuideItem("proot-distro list", "Shows available and installed distributions."),
                GuideItem("wget <URL>", "A non-interactive tool for downloading files from the web."),
            )
        ),
        GuideCategory(
            title = "Chapter 5: Process, Job, & Session Control",
            description = "Move from a casual user to a power user. Learn to manage running tasks, keep scripts alive in the background, and customize your shell session for maximum efficiency and control.",
            items = listOf(
                GuideItem("ps aux", "Lists all running processes associated with your user with details."),
                GuideItem("kill <PID>", "Terminates a process gracefully using its Process ID (PID)."),
                GuideItem("kill -9 <PID>", "Forcibly kills a stubborn or frozen process."),
                GuideItem("pkill <process_name>", "Kills a process based on its name instead of its PID."),
                GuideItem("pgrep <process_name>", "Searches for a process by name and prints its PID."),
                GuideItem("jobs", "Displays tasks running in the background of your current session."),
                GuideItem("Ctrl+Z", "Suspends the current foreground process and moves it to the background."),
                GuideItem("bg", "Resumes a suspended job and keeps it running in the background."),
                GuideItem("fg %<job_number>", "Brings a background job to the foreground, making it interactive."),
                GuideItem("command &", "Appending `&` to any command starts it directly in the background."),
                GuideItem("disown", "Detaches a background job from the current session so it won't be killed on exit."),
                GuideItem("termux-wake-lock", "Prevents the device from entering deep sleep, essential for servers."),
                GuideItem("termux-wake-unlock", "Releases the wake lock, allowing the device to sleep normally."),
                GuideItem("termux-reload-settings", "Applies changes from `~/.termux/termux.properties` without a restart."),
                GuideItem("termux-info", "Displays important diagnostic information about your Termux installation."),
                GuideItem("env", "Prints a list of all environment variables."),
                GuideItem("export VAR=\"value\"", "Sets an environment variable for the current session."),
                GuideItem("unset VAR", "Deletes an environment variable."),
                GuideItem("alias shortcut='long command'", "Creates a custom command shortcut."),
                GuideItem("unalias shortcut", "Removes a previously created alias."),
                GuideItem("source <file>", "Executes commands from a file in the current shell."),
                GuideItem("history", "Displays a list of the commands you've recently used."),
                GuideItem("uptime", "Shows how long the system has been running and load averages."),
                GuideItem("dmesg", "Prints messages from the kernel ring buffer, for hardware diagnostics."),
                GuideItem("nohup <command> &", "Runs a command that ignores the hangup signal, keeping it alive after exit."),
                GuideItem("htop", "Provides an interactive view of processes and resource usage (`pkg install htop`)."),
            )
        ),
        GuideCategory(
            title = "Chapter 6: Advanced File & Text Manipulation",
            description = "Unlock the true power of the shell by learning to process data. These native utilities are the cornerstone of the command line, allowing you to search, filter, and transform text and files with precision and speed.",
            items = listOf(
                GuideItem("grep <\"pattern\"> <file>", "Searches for a specific pattern of text within a file."),
                GuideItem("grep -r <\"pattern\"> <directory>", "Recursively searches for a pattern in all files within a directory."),
                GuideItem("grep -i <\"pattern\"> <file>", "Performs a case-insensitive search."),
                GuideItem("find <dir> -name \"<filename>\"", "Searches for files by name within a directory hierarchy."),
                GuideItem("find . -type f -mtime -1", "Finds files (`-type f`) in the current directory (`.`) modified in the last day."),
                GuideItem("sed 's/old/new/g' <file>", "A stream editor that can find and replace text."),
                GuideItem("awk '{print \$1}' <file>", "A pattern-scanning language. This prints the first word of every line."),
                GuideItem("cut -c 1-10 <file>", "Cuts out and prints the first 10 characters of each line."),
                GuideItem("cut -d',' -f2 <file.csv>", "Extracts the second field (`-f2`) from a CSV file using a comma delimiter."),
                GuideItem("tr 'a-z' 'A-Z' < <file>", "Translates characters. This converts a file's content to uppercase."),
                GuideItem("sort <file>", "Sorts the lines of a text file alphabetically."),
                GuideItem("sort -n <file>", "Sorts lines numerically."),
                GuideItem("uniq <file>", "Discards all but one of successive identical lines (use after `sort`)."),
                GuideItem("wc <file>", "Counts the number of lines, words, and characters in a file."),
                GuideItem("diff <file1> <file2>", "Compares two files line by line and shows the differences."),
                GuideItem("head -n 20 <file>", "Displays the first 20 lines of a file."),
                GuideItem("tail -n 20 <file>", "Displays the last 20 lines of a file."),
                GuideItem("tail -f <logfile>", "\"Follows\" a file, showing new lines as they are added in real time."),
                GuideItem("tee <filename>", "Reads input and writes it to both the screen and a file simultaneously."),
                GuideItem("ln -s <target> <link>", "Creates a symbolic link (a shortcut) to a file or directory."),
                GuideItem("stat <file>", "Displays detailed information about a file (size, permissions, etc.)."),
                GuideItem("file <file>", "Determines and prints the type of a file (e.g., ASCII text, JPEG image)."),
                GuideItem("strings <binary_file>", "Prints the printable character sequences from a binary file."),
                GuideItem("hexdump -C <file>", "Displays file content in hexadecimal and ASCII format."),
                GuideItem("base64 <file>", "Encodes a file to Base64 text."),
                GuideItem("base64 -d <file.b64>", "Decodes a Base64 file back to its original binary form."),
            )
        ),
        GuideCategory(
            title = "Chapter 7: Scripting & Automation",
            description = "Combine individual commands into powerful scripts to automate repetitive tasks. This chapter covers the essential building blocks of shell scripting, from user input and logic to controlling command execution flow.",
            items = listOf(
                GuideItem("read variable", "Pauses a script to wait for user input and stores it in a variable."),
                GuideItem("echo \"message\"", "Prints text to the terminal, essential for feedback in scripts."),
                GuideItem("printf \"format\" \"text\"", "A more powerful way to print formatted text."),
                GuideItem("sleep <seconds>", "Pauses the execution of a script for a specified number of seconds."),
                GuideItem("[ -f \"file.txt\" ]", "`test` expression to check for conditions, the basis of `if` statements."),
                GuideItem("xargs", "Builds and executes commands from standard input."),
                GuideItem("\$(command)", "Command Substitution. Runs a command and substitutes its output."),
                GuideItem("> (Redirect)", "Redirects command output to a file, overwriting it."),
                GuideItem(">> (Append)", "Redirects output and appends it to the end of a file."),
                GuideItem("< (Redirect Input)", "Uses a file as the input for a command."),
                GuideItem("2> (Redirect Error)", "Redirects only the error messages (stderr) to a file."),
                GuideItem("&> (Redirect All)", "Redirects both standard output and error to the same file."),
                GuideItem("&& (AND Operator)", "Executes the second command only if the first command succeeds."),
                GuideItem("; (Separator)", "Executes commands sequentially, regardless of success or failure."),
                GuideItem("basename /path/to/file.txt", "Strips the directory path, leaving only the filename (`file.txt`)."),
                GuideItem("dirname /path/to/file.txt", "Strips the filename, leaving only the directory path (`/path/to`)."),
                GuideItem("getopt", "Parses command-line options in scripts."),
                GuideItem("termux-job-scheduler -s <script>", "Schedules a script to run periodically, even when Termux is inactive."),
                GuideItem("termux-dialog | jq '.text'", "A scripting pattern to get and parse user input."),
                GuideItem("true", "A command that does nothing and always succeeds (exit code 0)."),
                GuideItem("false", "A command that does nothing and always fails (exit code 1)."),
                GuideItem("sh <script.sh>", "Executes a shell script."),
                GuideItem("chmod +x <script.sh>", "Makes a script executable, so you can run it directly with `./script.sh`."),
                GuideItem("seq <start> <end>", "Prints a sequence of numbers, useful for `for` loops."),
            )
        ),
        GuideCategory(
            title = "Chapter 8: Storage & Archive Management",
            description = "Effectively manage files, archives, and permissions. This chapter covers essential tools for compressing and decompressing data, understanding disk usage, and controlling access to your files.",
            items = listOf(
                GuideItem("chmod <permissions> <file>", "Changes the access permissions of a file (read, write, execute)."),
                GuideItem("chmod 755 <file>", "A common permission set for executables (owner: rwx, group/others: r-x)."),
                GuideItem("chown <user>:<group> <file>", "Changes the owner and group of a file (useful in proot environments)."),
                GuideItem("du -h", "Displays disk usage of files and directories in a human-readable format."),
                GuideItem("du -sh <directory>", "Shows the total size of a single directory (`-s` for summary)."),
                GuideItem("tar -czvf <archive.tar.gz> <dir>", "Creates a compressed archive (c: create, z: gzip, v: verbose, f: file)."),
                GuideItem("tar -xzvf <archive.tar.gz>", "Extracts a compressed archive (x: extract)."),
                GuideItem("tar -tvf <archive.tar.gz>", "Lists the contents of an archive without extracting it (t: list)."),
                GuideItem("gzip <file>", "Compresses a file, replacing it with a `.gz` version."),
                GuideItem("gunzip <file.gz>", "Decompresses a `.gz` file."),
                GuideItem("zip <archive.zip> <files>", "Creates a `.zip` archive."),
                GuideItem("unzip <archive.zip>", "Extracts files from a `.zip` archive."),
                GuideItem("bzip2 <file>", "Compresses a file using the bzip2 algorithm."),
                GuideItem("bunzip2 <file.bz2>", "Decompresses a `.bz2` file."),
                GuideItem("xz <file>", "Compresses a file using the xz algorithm (high compression)."),
                GuideItem("unxz <file.xz>", "Decompresses an `.xz` file."),
                GuideItem("termux-storage-get <file>", "Uses the system's file picker to copy a file into the current directory."),
                GuideItem("ls -l", "Long listing format, shows permissions, ownership, size, and date."),
                GuideItem("ls -a", "Lists all files, including hidden files (starting with a dot)."),
                GuideItem("ls -lh", "Combines long listing with human-readable file sizes."),
                GuideItem("df -hT", "Shows disk space usage for filesystems, including their type (`-T`)."),
                GuideItem("mount", "Displays all mounted filesystems."),
                GuideItem("readlink -f <file>", "Follows a symbolic link to find the real path of the original file."),
                GuideItem("dd if=/dev/zero of=dummy bs=1M", "A low-level command to create a file of a specific size for testing."),
                GuideItem("shred <file>", "Securely deletes a file by overwriting it multiple times."),
                GuideItem("pwd -L", "Prints the logical current working directory (respecting symlinks)."),
            )
        ),
        GuideCategory(
            title = "Chapter 9: Advanced Networking & Secure Connections",
            description = "Go beyond `ping`. This chapter covers the tools for secure remote access, robust file transfers, and in-depth network diagnostics, transforming Termux into a fully-featured network administration client.",
            items = listOf(
                GuideItem("ssh <user@host>", "Secure Shell client for logging into a remote server securely."),
                GuideItem("sshd", "The OpenSSH server daemon; run this to `ssh` into your Termux device."),
                GuideItem("ssh-keygen", "Generates a pair of cryptographic keys for passwordless SSH login."),
                GuideItem("ssh-copy-id <user@host>", "Copies your public key to a server to enable passwordless login."),
                GuideItem("scp <user@host:remote/file> <local>", "Securely copies files over SSH."),
                GuideItem("sftp <user@host>", "An interactive secure file transfer program over an SSH connection."),
                GuideItem("rsync -avh <source> <dest>", "A powerful tool for efficiently synchronizing files and directories."),
                GuideItem("curl <URL>", "A versatile tool to transfer data from or to a server (download, test APIs)."),
                GuideItem("curl -L <URL>", "Tells curl to follow any HTTP redirects."),
                GuideItem("curl -o <filename> <URL>", "Saves the output to a specific file."),
                GuideItem("wget <URL>", "A simple, non-interactive utility for downloading files from the web."),
                GuideItem("wget -c <URL>", "Continues a partially downloaded file."),
                GuideItem("wget -r <URL>", "Downloads a website recursively."),
                GuideItem("telnet <host> <port>", "An unencrypted tool for testing if a network port is open."),
                GuideItem("hostname", "Displays the device's network hostname."),
                GuideItem("ip -s link", "Shows detailed statistics for your network interfaces (bytes, errors)."),
                GuideItem("arp", "Displays the system's Address Resolution Protocol (ARP) cache."),
                GuideItem("termux-contact-list | jq", "API pattern to get and parse data (e.g., scripting contact lookups)."),
                GuideItem("termux-wifi-scaninfo | jq", "API pattern to get and parse info on nearby Wi-Fi networks."),
                GuideItem("ping -c 5 google.com", "Pings a host 5 times (`-c 5`) and then stops."),
                GuideItem("whois <domain.com>", "Retrieves registration information for a domain name."),
                GuideItem("dig <domain.com>", "A powerful DNS lookup utility."),
                GuideItem("nslookup <domain.com>", "Another command for querying DNS servers."),
                GuideItem("netstat -r", "Displays the kernel routing table."),
                GuideItem("netstat -i", "Displays a table of all network interfaces."),
                GuideItem("lsof -i", "Lists processes that are using the network."),
            )
        ),
        GuideCategory(
            title = "Chapter 10: System Internals & Diagnostics",
            description = "For the expert user. These commands let you look under the hood of the Termux environment and the underlying Android system, providing powerful tools for debugging, inspection, and advanced configuration.",
            items = listOf(
                GuideItem("termux-chroot", "Sets up a traditional Linux-like chroot environment."),
                GuideItem("login", "A command that gives you a clean login shell, often used after `termux-chroot`."),
                GuideItem("id", "Displays user and group information."),
                GuideItem("getprop", "Displays a huge list of Android system properties."),
                GuideItem("getprop | grep model", "A practical example: filtering system properties to find the device model."),
                GuideItem("logcat", "Dumps a log of Android system messages, invaluable for debugging."),
                GuideItem("logcat -s \"TAG\"", "Filters logcat output to show only messages with a specific tag."),
                GuideItem("ldd <binary>", "Prints the shared library dependencies of a program."),
                GuideItem("strace <command>", "Traces system calls and signals, showing what a program is doing."),
                GuideItem("uname -a", "Prints all available system information (kernel, architecture, etc.)."),
                GuideItem("arch", "Prints the machine's architecture (e.g., `aarch64`)."),
                GuideItem("free -h", "Displays free and used RAM in a human-readable format."),
                GuideItem("vmstat", "Reports information about processes, memory, paging, and CPU activity."),
                GuideItem("termux-api-start", "A script to ensure the `termux-api` background process is running."),
                GuideItem("termux-notification-list", "Retrieves a JSON list of all active notifications posted by Termux."),
                GuideItem("pkg policy", "Displays information about package versions and repository priorities."),
                GuideItem("pkg clean", "Clears out the cache of downloaded package files (`.deb`)."),
                GuideItem("pkg autoclean", "Removes old, no-longer-downloadable package files from the cache."),
                GuideItem("TERM=xterm-256color", "Sets the `TERM` variable to enable full color support in console programs."),
                GuideItem("reset", "Resets the terminal to its default state, fixing a garbled display."),
                GuideItem("stty -a", "Displays all the settings for the current terminal."),
                GuideItem("set -x", "Enables debugging mode in a shell script, printing each command."),
                GuideItem("set +x", "Disables debugging mode."),
                GuideItem("hash", "Shows a list of cached command locations for the current shell session."),
                GuideItem("type <command>", "Indicates how a command would be interpreted (alias, built-in, file)."),
                GuideItem("bind -p", "Lists all the keybindings and macros available in your shell."),
            )
        ),
    )
}
