plugins {
    alias(libs.plugins.androidLibrary)
    
}

android {
    namespace 'com.termux.shared'
    compileSdk 37

    defaultConfig {
        minSdk 24
    }

    androidResources {
        enable = true
    }

    externalNativeBuild {
        ndkBuild {
            path 'src/main/cpp/Android.mk'
        }
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.annotation
    implementation libs.androidx.core
    implementation libs.material
    implementation libs.guava
    implementation libs.core
    implementation libs.ext.strikethrough
    implementation libs.linkify
    implementation libs.recycler
    implementation libs.androidx.window
    implementation libs.commons.io
    api project(':terminal-emulator')
    implementation libs.termux.am.library
}
