package com.hereliesaz.hg2gui.terminal

import android.content.Context
import android.system.Os
import java.io.File
import java.nio.file.Files

/**
 * Repairs bootstrap details that older HG2Gui installs may have extracted before the current
 * relocation fixes existed. A bootstrap is persistent across APK updates, so extraction-time
 * fixes alone do not repair an already-installed prefix.
 */
object TermuxRuntimeRepair {
    private const val TERMUX_PREFIX = "/data/data/com.termux/files/usr"
    private const val WRAPPERS = ".hg2gui-script-wrappers.sh"
    private const val PROFILE_LINE = "[ -f \"\$HOME/$WRAPPERS\" ] && . \"\$HOME/$WRAPPERS\""

    fun repair(context: Context) {
        val prefix = DistroManager.prefixDir(context)
        val bin = File(prefix, "bin")
        if (!prefix.isDirectory || !bin.isDirectory) return

        // Termux's bootstrap contains executable helper scripts outside bin as well. apt is a
        // particularly important example: bin/apt-key invokes helpers under libexec/apt/, and
        // those helpers carry Termux's original package-specific interpreter path. Rewriting only
        // bin therefore lets pkg/apt start but makes signature verification fail later with the
        // misleading "Couldn't execute .../bin/apt-key" / "repository is not signed" error.
        // Walk every executable-script-bearing prefix tree, but only rewrite shebang-gated text
        // files so ELF binaries and package data are never touched.
        listOf("bin", "libexec", "lib").forEach { subdir ->
            val root = File(prefix, subdir)
            if (!root.exists()) return@forEach
            root.walkTopDown().forEach { file -> repairScript(file, prefix) }
        }

        repairMainRepoKey(prefix)
        writeAptConfig(prefix)
        writeScriptWrappers(prefix, DistroManager.homeDir(context))
    }

    private fun repairScript(file: File, prefix: File) {
        if (!file.isFile || Files.isSymbolicLink(file.toPath()) || isElf(file)) return
        val bytes = runCatching { file.readBytes() }.getOrNull() ?: return
        if (bytes.size < 2 || bytes[0] != '#'.code.toByte() || bytes[1] != '!'.code.toByte()) return
        val text = String(bytes, Charsets.UTF_8)
        if (TERMUX_PREFIX in text) {
            runCatching {
                file.writeBytes(text.replace(TERMUX_PREFIX, prefix.absolutePath).toByteArray(Charsets.UTF_8))
            }
        }
        runCatching { file.setExecutable(true) }
    }

    private fun repairMainRepoKey(prefix: File) {
        val target = File(prefix, "share/termux-keyring/termux-pacman.gpg")
        if (!target.exists()) return
        val link = File(prefix, "etc/apt/trusted.gpg.d/termux-pacman.gpg")
        link.parentFile?.mkdirs()
        if (runCatching { link.canonicalPath == target.canonicalPath }.getOrDefault(false)) return
        runCatching { link.delete() }
        runCatching { Os.symlink(target.absolutePath, link.absolutePath) }
    }

    private fun writeAptConfig(prefix: File) {
        val p = prefix.absolutePath
        File(prefix, "var/cache/apt/archives/partial").mkdirs()
        File(prefix, "var/lib/apt/lists/partial").mkdirs()
        val etc = File(prefix, "etc/apt").apply { mkdirs() }
        File(etc, "apt.conf").writeText(
            """
            Dir "$p/";
            Dir::Etc "$p/etc/apt/";
            Dir::Etc::sourcelist "$p/etc/apt/sources.list";
            Dir::Etc::sourceparts "$p/etc/apt/sources.list.d/";
            Dir::Etc::vendorlist "$p/etc/apt/vendors.list";
            Dir::Etc::vendorparts "$p/etc/apt/vendors.list.d/";
            Dir::Etc::main "$p/etc/apt/apt.conf";
            Dir::Etc::parts "$p/etc/apt/apt.conf.d/";
            Dir::Etc::preferences "$p/etc/apt/preferences";
            Dir::Etc::preferencesparts "$p/etc/apt/preferences.d/";
            Dir::Etc::trusted "$p/etc/apt/trusted.gpg";
            Dir::Etc::trustedparts "$p/etc/apt/trusted.gpg.d/";
            Dir::State "$p/var/lib/apt/";
            Dir::State::lists "$p/var/lib/apt/lists/";
            Dir::State::status "$p/var/lib/dpkg/status";
            Dir::Cache "$p/var/cache/apt/";
            Dir::Cache::archives "$p/var/cache/apt/archives/";
            Dir::Log "$p/var/log/apt/";
            Dir::Bin::methods "$p/lib/apt/methods/";
            Dir::Bin::solvers:: "$p/lib/apt/solvers/";
            Dir::Bin::dpkg "$p/bin/dpkg";
            Acquire::https::CaInfo "$p/etc/tls/cert.pem";
            """.trimIndent()
        )
    }

    private fun writeScriptWrappers(prefix: File, home: File) {
        home.mkdirs()
        val scripts = File(prefix, "bin").listFiles().orEmpty()
            .filter { it.isFile && !Files.isSymbolicLink(it.toPath()) && !isElf(it) }
            .map { it.name }
            .sorted()

        File(home, WRAPPERS).writeText(buildString {
            appendLine("# Auto-generated by HG2Gui. Do not edit.")
            scripts.forEach { name ->
                appendLine("$name() ( source \"\$PREFIX/bin/$name\" \"\$@\" )")
            }
        })

        val profile = File(home, ".bash_profile")
        val existing = if (profile.exists()) profile.readText() else ""
        if (PROFILE_LINE !in existing) {
            profile.appendText((if (existing.isNotEmpty() && !existing.endsWith('\n')) "\n" else "") + PROFILE_LINE + "\n")
        }
    }

    private fun isElf(file: File): Boolean = runCatching {
        file.inputStream().use { input ->
            val magic = ByteArray(4)
            input.read(magic) == 4 && magic[0].toInt() == 0x7f &&
                magic[1] == 'E'.code.toByte() && magic[2] == 'L'.code.toByte() && magic[3] == 'F'.code.toByte()
        }
    }.getOrDefault(false)
}
