plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinAndroid)
}

android {
    namespace 'com.termux.emulator'
    compileSdk 37

    defaultConfig {
        minSdk 24
    }

    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }
}

dependencies {
    implementation libs.androidx.annotation
}
